platform :ios, '11.0'
use_frameworks!

def common_pods
  pod 'Alamofire'
  pod 'UIColor_Hex_Swift'
  pod 'Kanna'
  pod 'SDWebImage'
  pod 'AttributedLib'
end

target 'Metal Archives' do
    common_pods
    pod 'AlamofireNetworkActivityIndicator'
    pod 'Toaster'
    pod 'Charts'
    pod 'SkyFloatingLabelTextField'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Crashlytics'
    pod 'Siren'
    pod 'NotificationBannerSwift'
    pod 'MBProgressHUD'
    pod 'KeychainAccess'
    pod 'MaterialComponents/Snackbar'
    pod 'Floaty'
end

target 'Metal Archives Widget' do
     common_pods
end

target 'Metal ArchivesTests' do
    pod 'Kanna'
end
